# Welcome to Jekyll!

# Website settings
title: Aswathy Mohan
description: Hi.
keywords: deep learning, ai, data science, python, pandas, keras

#baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://DeepLearnerCNN.github.io/aswathy.mohan # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Aswathy Mohan  # Be used at blog posts' author.
  first_name: Aswathy  # Be used at index page about me section.
  last_name: Mohan  # Be used at index page about me section.
  avatar: /static/assets/img/landing/my_logo.jpg  # upload your avatar at directory and edit it.
  github_username: DeepLearnerCNN  # Leave blank if you don't have now
  linkedin_id: aswathy1891989 # Leave blank if you don't have now
  facebook_username: aswathy18989  # Leave blank if you don't have now
  twitter_username: aswathy1891989  # Leave blank if you don't have now
  email: aswathy1891989@gmail.com  # Leave blank if you don't have now # Leave blank if you don't have now
  cv: Aswathy_CV.pdf # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: icon-python
    - name: icon-git
  skill_icon3:
    - name: icon-javascript-alt
    - name: fa-linux
 
  desc: I am an Independent Self Paced Learner, working on Machine Learning and Convolutional Neural Networks.
        I have done my Master's in Computer Science, with passion in doing research in AI and Machine Learning,
        data analysis and decision making. From Associate Consultant in Oracle and Assistant Professor in  College, 
        and I’ve developed a deep understanding of the importance of data and decision making over my two years in the field.
        Currently, I work on Kaggle Datasets, where I am focused on analyzing and prediction. For detailed CV click on the pdf icon above
        
  
        
  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
#kramdown:
 # input: GFM
  #syntax_highlighter: rouge
  
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  syntax_highlighter: rouge

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

